server:
  port: 9060
  servlet:
    context-path: /api

spring:
  application:
    name: gateway-api
  security:
    user:
      name: admin
      password: 123456
  cloud:
    gateway:
      discovery:
        locator:
          #表明gateway开启服务注册和发现的功能，
          #并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，
          #这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          lower-case-service-id: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、
      #一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。
      routes:
        - id: feign-client-route
          uri: lb://feign-client
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            - Path=/feign/**
          filters:
           - StripPrefix=1
        - id: ribbon-client-route
          uri: lb://ribbon-client
          predicates:
            - Path=/ribbon/**
          filters:
            - StripPrefix=1

eureka:
  #自己编写，用于修改注册中心的服务地址
  serverUrl: 127.0.0.1
  port: 9010
  hostname: ${spring.cloud.client.ip-address}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.serverUrl}:${eureka.port}/eureka/
  instance:
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}(${spring.application.name})
    prefer-ip-address: true
    appname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 3 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
