server:
  port: 9060

spring:
  application:
    name: gateway-api
  security:
    user:
      name: admin
      password: 123456
  redis:
    host: 192.168.0.21
    port: 6379
    password:
    timeout: 200
    database: 1
  cloud:
    gateway:
      discovery:
        locator:
          #表明gateway开启服务注册和发现的功能，
          #并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，
          #这个router将以服务名开头的请求路径转发到对应的服务
          enabled: true
          lower-case-service-id: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、
      #一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。
      routes:
        - id: feign-client-route
          uri: lb://feign-client
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            - Path=/feign/**
          filters:
            - StripPrefix=1
            - name:  Hystrix
              args:
                name: fallbackCmd
                fallbackUri: forward:/fallback #fallback对应的uri
            - name: RequestRateLimiter #限流
              args:
                key-resolver: "#{@ipAddrKeyResolver}" #使用SpEL按名称引用bean
                redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率,即行等价于允许用户每秒处理多少个请求平均数
                redis-rate-limiter.burstCapacity: 2 #令牌桶的容量，允许在一秒钟内完成的最大请求数（用的是令牌桶算法）
        - id: ribbon-client-route
          uri: lb://ribbon-client
          predicates:
            - Path=/ribbon/**
          filters:
            - StripPrefix=1

## hystrix设置隔离策略为信号量，超时时间为2秒
hystrix:
  command:
    fallbackCmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


eureka:
  #自己编写，用于修改注册中心的服务地址
  serverUrl: 127.0.0.1
  port: 9010
  hostname: ${spring.cloud.client.ip-address}
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.serverUrl}:${eureka.port}/eureka/
  instance:
    instance-id:  ${spring.cloud.client.ip-address}:${server.port}(${spring.application.name})
    prefer-ip-address: true
    appname: ${spring.application.name}
    lease-renewal-interval-in-seconds: 3 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
